name: Linting

# Controls when the workflow will run
on:
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  linting:
    name: linting
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
        matrix:
            python-version: [3.6.9]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Install Depedencies
        run: 
          python3 -m pip install black==21.12b0
          python3 -m pip install isort==5.10.1
          python3 -m pip install flake8==4.0.1
          python3 -m pip install mypy==0.931
          
      - name: black
        run:
          black .
      
      - name: isort
        run:
          isort .
      
      - name: flake8
        run:
          flake8 .

      - name: mypy
        run:
          mypy .
